### ISSUE TITLE
Services not loaded on HTTPS enabled

### ISSUE THREAD

**Issue by amouhoub** [ow2-proactive/automation-dashboard#111]
When you activate HTTPS in`config/web/settings.ini`, the services are not loaded and they don't appear in the catalog.

To understand this error, activate the network console and reload the services page (Cloud-Automation). As you can see in the attached screenshot, the automation-dashboard still sends the request to the server (localhost) over HTTP using PORT 8080 instead of sending it to HTTPS over 8443.
There should be a forwarding mechanism or an alternate default server path when the https is enabled.

This also causes an authentification issue in scheduler-portal and rm (they still use the old login page) probably due to the same reason.

<img width="1440" alt="capture d ecran 2018-03-13 a 13 12 12" src="https://user-images.githubusercontent.com/1918419/37393900-ba78c5ec-2772-11e8-9ea9-66aad83f4fba.png">

**Comment by fviale** [comment]
It is not enough the change the protocol to https in config/web/settings.ini

All microservices must also be configured in dist/war/microservice/WEB-INF/classes/application.properties

Also the scheduler and rm portal must be configured in:
dist/war/scheduler/scheduler.conf
dist/war/rm/rm.conf

**Comment by amouhoub** [comment]
@fviale should I close the issue since it is not really an issue?

**Comment by fviale** [comment]
yes please

**Comment by amouhoub** [comment]
I'm closing this as it is not an issue but caused by an improper configuration
