### ISSUE TITLE
Not able to login with `Enter`

### ISSUE THREAD

**Issue by ShatalovYaroslav** [ow2-proactive/automation-dashboard#246]
On the login page only in Firefox, after filling login, password fields: can not login pressing `Enter`.  
It's still possible to login with `connect` button.
This works for example in Chrome.

**Comment by medou-boushab** [comment]
In Chrome it doesn't work as well

**Comment by chloegugli** [comment]
I'm working on a fix

**Comment by chloegugli** [comment]
https://github.com/ow2-proactive/automation-dashboard/pull/247
